
package mn.gov.ema.emongolia.data.XypEducation;

import mn.gov.ema.emongolia.data.ServiceResponse.ServiceResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EducationService", targetNamespace = "http://education.xyp.gov.mn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EducationService {


    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypEducation.ServiceResponse
     */
    @WebMethod(operationName = "WS400103_childrenInfoByParentCivilId")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS400103_childrenInfoByParentCivilId", targetNamespace = "http://education.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypEducation.WS400103ChildrenInfoByParentCivilId")
    @ResponseWrapper(localName = "WS400103_childrenInfoByParentCivilIdResponse", targetNamespace = "http://education.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypEducation.WS400103ChildrenInfoByParentCivilIdResponse")
    public ServiceResponse ws400103ChildrenInfoByParentCivilId(
        @WebParam(name = "request", targetNamespace = "")
        RegistrationCivilIdRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypEducation.ServiceResponse
     */
    @WebMethod(operationName = "WS400105_checkKindergartenEnrollment")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS400105_checkKindergartenEnrollment", targetNamespace = "http://education.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypEducation.WS400105CheckKindergartenEnrollment")
    @ResponseWrapper(localName = "WS400105_checkKindergartenEnrollmentResponse", targetNamespace = "http://education.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypEducation.WS400105CheckKindergartenEnrollmentResponse")
    public ServiceResponse ws400105CheckKindergartenEnrollment(
        @WebParam(name = "request", targetNamespace = "")
        CivilIdRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypEducation.ServiceResponse
     */
    @WebMethod(operationName = "WS400101_ueeReferenceService")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS400101_ueeReferenceService", targetNamespace = "http://education.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypEducation.WS400101UeeReferenceService")
    @ResponseWrapper(localName = "WS400101_ueeReferenceServiceResponse", targetNamespace = "http://education.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypEducation.WS400101UeeReferenceServiceResponse")
    public ServiceResponse ws400101UeeReferenceService(
        @WebParam(name = "request", targetNamespace = "")
        UeeReferenceRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypEducation.ServiceResponse
     */
    @WebMethod(operationName = "WS400102_kindergartenDescription")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS400102_kindergartenDescription", targetNamespace = "http://education.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypEducation.WS400102KindergartenDescription")
    @ResponseWrapper(localName = "WS400102_kindergartenDescriptionResponse", targetNamespace = "http://education.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypEducation.WS400102KindergartenDescriptionResponse")
    public ServiceResponse ws400102KindergartenDescription(
        @WebParam(name = "request", targetNamespace = "")
        RegnumRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypEducation.ServiceResponse
     */
    @WebMethod(operationName = "WS400104_sendKindergartenEnrollment")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS400104_sendKindergartenEnrollment", targetNamespace = "http://education.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypEducation.WS400104SendKindergartenEnrollment")
    @ResponseWrapper(localName = "WS400104_sendKindergartenEnrollmentResponse", targetNamespace = "http://education.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypEducation.WS400104SendKindergartenEnrollmentResponse")
    public ServiceResponse ws400104SendKindergartenEnrollment(
        @WebParam(name = "request", targetNamespace = "")
        KindergartenEnrollmentRequestData request);

}
