
package mn.gov.ema.emongolia.data.XypEducation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EducationServiceService", targetNamespace = "http://education.xyp.gov.mn/", wsdlLocation = "https://xyp.gov.mn/education-1.5.0/ws?WSDL")
public class EducationServiceService
    extends Service
{

    private final static URL EDUCATIONSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException EDUCATIONSERVICESERVICE_EXCEPTION;
    private final static QName EDUCATIONSERVICESERVICE_QNAME = new QName("http://education.xyp.gov.mn/", "EducationServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://xyp.gov.mn/education-1.5.0/ws?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EDUCATIONSERVICESERVICE_WSDL_LOCATION = url;
        EDUCATIONSERVICESERVICE_EXCEPTION = e;
    }

    public EducationServiceService() {
        super(__getWsdlLocation(), EDUCATIONSERVICESERVICE_QNAME);
    }

    public EducationServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EDUCATIONSERVICESERVICE_QNAME, features);
    }

    public EducationServiceService(URL wsdlLocation) {
        super(wsdlLocation, EDUCATIONSERVICESERVICE_QNAME);
    }

    public EducationServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EDUCATIONSERVICESERVICE_QNAME, features);
    }

    public EducationServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EducationServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EducationService
     */
    @WebEndpoint(name = "EducationServicePort")
    public EducationService getEducationServicePort() {
        return super.getPort(new QName("http://education.xyp.gov.mn/", "EducationServicePort"), EducationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EducationService
     */
    @WebEndpoint(name = "EducationServicePort")
    public EducationService getEducationServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://education.xyp.gov.mn/", "EducationServicePort"), EducationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EDUCATIONSERVICESERVICE_EXCEPTION!= null) {
            throw EDUCATIONSERVICESERVICE_EXCEPTION;
        }
        return EDUCATIONSERVICESERVICE_WSDL_LOCATION;
    }

}
