
package mn.gov.ema.emongolia.data.XypCitizen140;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CitizenService", targetNamespace = "http://citizen.xyp.gov.mn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CitizenService {


    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypCitizen140.ServiceResponse
     */
    @WebMethod(operationName = "WS100125_checkCitizenRegnum")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100125_checkCitizenRegnum", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100125CheckCitizenRegnum")
    @ResponseWrapper(localName = "WS100125_checkCitizenRegnumResponse", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100125CheckCitizenRegnumResponse")
    public ServiceResponse ws100125CheckCitizenRegnum(
        @WebParam(name = "request", targetNamespace = "")
        ServiceCheckCitizenRegnumRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypCitizen140.ServiceResponse
     */
    @WebMethod(operationName = "WS100102_getCitizenBirthInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100102_getCitizenBirthInfo", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100102GetCitizenBirthInfo")
    @ResponseWrapper(localName = "WS100102_getCitizenBirthInfoResponse", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100102GetCitizenBirthInfoResponse")
    public ServiceResponse ws100102GetCitizenBirthInfo(
        @WebParam(name = "request", targetNamespace = "")
        CitizenRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypCitizen140.ServiceResponse
     */
    @WebMethod(operationName = "WS100106_authorizeCitizen")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100106_authorizeCitizen", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100106AuthorizeCitizen")
    @ResponseWrapper(localName = "WS100106_authorizeCitizenResponse", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100106AuthorizeCitizenResponse")
    public ServiceResponse ws100106AuthorizeCitizen(
        @WebParam(name = "request", targetNamespace = "")
        CitizenRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypCitizen140.ServiceResponse
     */
    @WebMethod(operationName = "WS100138_getCitizenRegnumInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100138_getCitizenRegnumInfo", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100138GetCitizenRegnumInfo")
    @ResponseWrapper(localName = "WS100138_getCitizenRegnumInfoResponse", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100138GetCitizenRegnumInfoResponse")
    public ServiceResponse ws100138GetCitizenRegnumInfo(
        @WebParam(name = "request", targetNamespace = "")
        CitizenRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypCitizen140.ServiceResponse
     */
    @WebMethod(operationName = "WS100101_getCitizenIDCardInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100101_getCitizenIDCardInfo", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100101GetCitizenIDCardInfo")
    @ResponseWrapper(localName = "WS100101_getCitizenIDCardInfoResponse", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100101GetCitizenIDCardInfoResponse")
    public ServiceResponse ws100101GetCitizenIDCardInfo(
        @WebParam(name = "request", targetNamespace = "")
        CitizenRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypCitizen140.ServiceResponse
     */
    @WebMethod(operationName = "WS100103_getCitizenAddressInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100103_getCitizenAddressInfo", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100103GetCitizenAddressInfo")
    @ResponseWrapper(localName = "WS100103_getCitizenAddressInfoResponse", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100103GetCitizenAddressInfoResponse")
    public ServiceResponse ws100103GetCitizenAddressInfo(
        @WebParam(name = "request", targetNamespace = "")
        CitizenRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypCitizen140.ServiceResponse
     */
    @WebMethod(operationName = "WS100140_firstTimePassportInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100140_firstTimePassportInfo", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100140FirstTimePassportInfo")
    @ResponseWrapper(localName = "WS100140_firstTimePassportInfoResponse", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100140FirstTimePassportInfoResponse")
    public ServiceResponse ws100140FirstTimePassportInfo(
        @WebParam(name = "request", targetNamespace = "")
        CitizenRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypCitizen140.ServiceResponse
     */
    @WebMethod(operationName = "WS100117_checkCitizenAddressInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100117_checkCitizenAddressInfo", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100117CheckCitizenAddressInfo")
    @ResponseWrapper(localName = "WS100117_checkCitizenAddressInfoResponse", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100117CheckCitizenAddressInfoResponse")
    public ServiceResponse ws100117CheckCitizenAddressInfo(
        @WebParam(name = "request", targetNamespace = "")
        ServiceCheckCitizenAddressInfoRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypCitizen140.ServiceResponse
     */
    @WebMethod(operationName = "WS100134_getCitizenChangeNameInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100134_getCitizenChangeNameInfo", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100134GetCitizenChangeNameInfo")
    @ResponseWrapper(localName = "WS100134_getCitizenChangeNameInfoResponse", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100134GetCitizenChangeNameInfoResponse")
    public ServiceResponse ws100134GetCitizenChangeNameInfo(
        @WebParam(name = "request", targetNamespace = "")
        CitizenRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypCitizen140.ServiceResponse
     */
    @WebMethod(operationName = "WS100128_getCitizenNoMarriageInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100128_getCitizenNoMarriageInfo", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100128GetCitizenNoMarriageInfo")
    @ResponseWrapper(localName = "WS100128_getCitizenNoMarriageInfoResponse", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100128GetCitizenNoMarriageInfoResponse")
    public ServiceResponse ws100128GetCitizenNoMarriageInfo(
        @WebParam(name = "request", targetNamespace = "")
        CitizenRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypCitizen140.ServiceResponse
     */
    @WebMethod(operationName = "WS100139_getCitizenChangeRegnumInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100139_getCitizenChangeRegnumInfo", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100139GetCitizenChangeRegnumInfo")
    @ResponseWrapper(localName = "WS100139_getCitizenChangeRegnumInfoResponse", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100139GetCitizenChangeRegnumInfoResponse")
    public ServiceResponse ws100139GetCitizenChangeRegnumInfo(
        @WebParam(name = "request", targetNamespace = "")
        CitizenRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypCitizen140.ServiceResponse
     */
    @WebMethod(operationName = "WS100110_passportInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100110_passportInfo", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100110PassportInfo")
    @ResponseWrapper(localName = "WS100110_passportInfoResponse", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100110PassportInfoResponse")
    public ServiceResponse ws100110PassportInfo(
        @WebParam(name = "request", targetNamespace = "")
        ServicePassortInfoRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypCitizen140.ServiceResponse
     */
    @WebMethod(operationName = "WS100107_checkCitizenInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100107_checkCitizenInfo", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100107CheckCitizenInfo")
    @ResponseWrapper(localName = "WS100107_checkCitizenInfoResponse", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100107CheckCitizenInfoResponse")
    public ServiceResponse ws100107CheckCitizenInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckCitizenInfoRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypCitizen140.ServiceResponse
     */
    @WebMethod(operationName = "WS100105_getCitizenMarriageDivorceInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100105_getCitizenMarriageDivorceInfo", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100105GetCitizenMarriageDivorceInfo")
    @ResponseWrapper(localName = "WS100105_getCitizenMarriageDivorceInfoResponse", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100105GetCitizenMarriageDivorceInfoResponse")
    public ServiceResponse ws100105GetCitizenMarriageDivorceInfo(
        @WebParam(name = "request", targetNamespace = "")
        CitizenRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypCitizen140.ServiceResponse
     */
    @WebMethod(operationName = "WS100141_passportInfoSecondTime")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100141_passportInfoSecondTime", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100141PassportInfoSecondTime")
    @ResponseWrapper(localName = "WS100141_passportInfoSecondTimeResponse", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100141PassportInfoSecondTimeResponse")
    public ServiceResponse ws100141PassportInfoSecondTime(
        @WebParam(name = "request", targetNamespace = "")
        CitizenRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypCitizen140.ServiceResponse
     */
    @WebMethod(operationName = "WS100104_getCitizenMarriageInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100104_getCitizenMarriageInfo", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100104GetCitizenMarriageInfo")
    @ResponseWrapper(localName = "WS100104_getCitizenMarriageInfoResponse", targetNamespace = "http://citizen.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypCitizen140.WS100104GetCitizenMarriageInfoResponse")
    public ServiceResponse ws100104GetCitizenMarriageInfo(
        @WebParam(name = "request", targetNamespace = "")
        CitizenRequestData request);

}
