
package mn.gov.ema.emongolia.data.XypTax;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TaxServiceService", targetNamespace = "http://tax.xyp.gov.mn/", wsdlLocation = "https://xyp.gov.mn/tax-1.5.0/ws?WSDL")
public class TaxServiceService
    extends Service
{

    private final static URL TAXSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException TAXSERVICESERVICE_EXCEPTION;
    private final static QName TAXSERVICESERVICE_QNAME = new QName("http://tax.xyp.gov.mn/", "TaxServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://xyp.gov.mn/tax-1.5.0/ws?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TAXSERVICESERVICE_WSDL_LOCATION = url;
        TAXSERVICESERVICE_EXCEPTION = e;
    }

    public TaxServiceService() {
        super(__getWsdlLocation(), TAXSERVICESERVICE_QNAME);
    }

    public TaxServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TAXSERVICESERVICE_QNAME, features);
    }

    public TaxServiceService(URL wsdlLocation) {
        super(wsdlLocation, TAXSERVICESERVICE_QNAME);
    }

    public TaxServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TAXSERVICESERVICE_QNAME, features);
    }

    public TaxServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaxServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TaxService
     */
    @WebEndpoint(name = "TaxServicePort")
    public TaxService getTaxServicePort() {
        return super.getPort(new QName("http://tax.xyp.gov.mn/", "TaxServicePort"), TaxService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaxService
     */
    @WebEndpoint(name = "TaxServicePort")
    public TaxService getTaxServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tax.xyp.gov.mn/", "TaxServicePort"), TaxService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TAXSERVICESERVICE_EXCEPTION!= null) {
            throw TAXSERVICESERVICE_EXCEPTION;
        }
        return TAXSERVICESERVICE_WSDL_LOCATION;
    }

}
