
package mn.gov.ema.emongolia.data.XypLegalEntity;

import mn.gov.ema.emongolia.data.ServiceResponse.ServiceResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LesService", targetNamespace = "http://les.xyp.gov.mn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LesService {


    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100314_citizenShareHolderCompanyInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100314_citizenShareHolderCompanyInfo", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100314CitizenShareHolderCompanyInfo")
    @ResponseWrapper(localName = "WS100314_citizenShareHolderCompanyInfoResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100314CitizenShareHolderCompanyInfoResponse")
    public ServiceResponse ws100314CitizenShareHolderCompanyInfo(
        @WebParam(name = "request", targetNamespace = "")
        NonLegalEntityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100329_energyLicenseCertificateInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100329_energyLicenseCertificateInfo", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100329EnergyLicenseCertificateInfo")
    @ResponseWrapper(localName = "WS100329_energyLicenseCertificateInfoResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100329EnergyLicenseCertificateInfoResponse")
    public ServiceResponse ws100329EnergyLicenseCertificateInfo(
        @WebParam(name = "request", targetNamespace = "")
        EnergyLicenseCertRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100325_legalEntityFinalOwnerInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100325_legalEntityFinalOwnerInfo", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100325LegalEntityFinalOwnerInfo")
    @ResponseWrapper(localName = "WS100325_legalEntityFinalOwnerInfoResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100325LegalEntityFinalOwnerInfoResponse")
    public ServiceResponse ws100325LegalEntityFinalOwnerInfo(
        @WebParam(name = "request", targetNamespace = "")
        LegalEntityFinalOwnerRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100310_legalEntityReorganizedInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100310_legalEntityReorganizedInfo", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100310LegalEntityReorganizedInfo")
    @ResponseWrapper(localName = "WS100310_legalEntityReorganizedInfoResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100310LegalEntityReorganizedInfoResponse")
    public ServiceResponse ws100310LegalEntityReorganizedInfo(
        @WebParam(name = "request", targetNamespace = "")
        EntityNumberData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100304_getLegalEntityNewlyCreatedInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100304_getLegalEntityNewlyCreatedInfo", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100304GetLegalEntityNewlyCreatedInfo")
    @ResponseWrapper(localName = "WS100304_getLegalEntityNewlyCreatedInfoResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100304GetLegalEntityNewlyCreatedInfoResponse")
    public ServiceResponse ws100304GetLegalEntityNewlyCreatedInfo(
        @WebParam(name = "request", targetNamespace = "")
        EntityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100322_legalEntityIndustryLicenseInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100322_legalEntityIndustryLicenseInfo", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100322LegalEntityIndustryLicenseInfo")
    @ResponseWrapper(localName = "WS100322_legalEntityIndustryLicenseInfoResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100322LegalEntityIndustryLicenseInfoResponse")
    public ServiceResponse ws100322LegalEntityIndustryLicenseInfo(
        @WebParam(name = "request", targetNamespace = "")
        LegalEntityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100330_liquidationInfoService")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100330_liquidationInfoService", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100330LiquidationInfoService")
    @ResponseWrapper(localName = "WS100330_liquidationInfoServiceResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100330LiquidationInfoServiceResponse")
    public ServiceResponse ws100330LiquidationInfoService(
        @WebParam(name = "request", targetNamespace = "")
        EntityNumberData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100328_checkLegalEntityNameInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100328_checkLegalEntityNameInfo", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100328CheckLegalEntityNameInfo")
    @ResponseWrapper(localName = "WS100328_checkLegalEntityNameInfoResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100328CheckLegalEntityNameInfoResponse")
    public ServiceResponse ws100328CheckLegalEntityNameInfo(
        @WebParam(name = "request", targetNamespace = "")
        LegalEntityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100305_searchLegalEntityName")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100305_searchLegalEntityName", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100305SearchLegalEntityName")
    @ResponseWrapper(localName = "WS100305_searchLegalEntityNameResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100305SearchLegalEntityNameResponse")
    public ServiceResponse ws100305SearchLegalEntityName(
        @WebParam(name = "request", targetNamespace = "")
        ServiceSearchLegalEntityNameRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100320_createInqCustoms")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100320_createInqCustoms", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100320CreateInqCustoms")
    @ResponseWrapper(localName = "WS100320_createInqCustomsResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100320CreateInqCustomsResponse")
    public ServiceResponse ws100320CreateInqCustoms(
        @WebParam(name = "request", targetNamespace = "")
        CreateInqCustomsRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100311_getLegalEntityInfoToTax")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100311_getLegalEntityInfoToTax", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100311GetLegalEntityInfoToTax")
    @ResponseWrapper(localName = "WS100311_getLegalEntityInfoToTaxResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100311GetLegalEntityInfoToTaxResponse")
    public ServiceResponse ws100311GetLegalEntityInfoToTax(
        @WebParam(name = "request", targetNamespace = "")
        EntityNumberData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100324_legalEntityGeneralInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100324_legalEntityGeneralInfo", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100324LegalEntityGeneralInfo")
    @ResponseWrapper(localName = "WS100324_legalEntityGeneralInfoResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100324LegalEntityGeneralInfoResponse")
    public ServiceResponse ws100324LegalEntityGeneralInfo(
        @WebParam(name = "request", targetNamespace = "")
        LegalEntityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100313_citizenLegalEntityList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100313_citizenLegalEntityList", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100313CitizenLegalEntityList")
    @ResponseWrapper(localName = "WS100313_citizenLegalEntityListResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100313CitizenLegalEntityListResponse")
    public ServiceResponse ws100313CitizenLegalEntityList(
        @WebParam(name = "request", targetNamespace = "")
        NonLegalEntityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100317_findLesNameInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100317_findLesNameInfo", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100317FindLesNameInfo")
    @ResponseWrapper(localName = "WS100317_findLesNameInfoResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100317FindLesNameInfoResponse")
    public ServiceResponse ws100317FindLesNameInfo(
        @WebParam(name = "request", targetNamespace = "")
        FindLesNameRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100312_checkDebtOfCustomsInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100312_checkDebtOfCustomsInfo", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100312CheckDebtOfCustomsInfo")
    @ResponseWrapper(localName = "WS100312_checkDebtOfCustomsInfoResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100312CheckDebtOfCustomsInfoResponse")
    public ServiceResponse ws100312CheckDebtOfCustomsInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckDebtOfCustomsRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100306_getNonLegalEntityInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100306_getNonLegalEntityInfo", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100306GetNonLegalEntityInfo")
    @ResponseWrapper(localName = "WS100306_getNonLegalEntityInfoResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100306GetNonLegalEntityInfoResponse")
    public ServiceResponse ws100306GetNonLegalEntityInfo(
        @WebParam(name = "request", targetNamespace = "")
        NonLegalEntityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100326_legalEntityStampInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100326_legalEntityStampInfo", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100326LegalEntityStampInfo")
    @ResponseWrapper(localName = "WS100326_legalEntityStampInfoResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100326LegalEntityStampInfoResponse")
    public ServiceResponse ws100326LegalEntityStampInfo(
        @WebParam(name = "request", targetNamespace = "")
        LegalEntityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100323_legalEntityNonPaymentInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100323_legalEntityNonPaymentInfo", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100323LegalEntityNonPaymentInfo")
    @ResponseWrapper(localName = "WS100323_legalEntityNonPaymentInfoResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100323LegalEntityNonPaymentInfoResponse")
    public ServiceResponse ws100323LegalEntityNonPaymentInfo(
        @WebParam(name = "request", targetNamespace = "")
        LegalEntityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100307_getLegalEntityInfoWithRegnum")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100307_getLegalEntityInfoWithRegnum", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100307GetLegalEntityInfoWithRegnum")
    @ResponseWrapper(localName = "WS100307_getLegalEntityInfoWithRegnumResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100307GetLegalEntityInfoWithRegnumResponse")
    public ServiceResponse ws100307GetLegalEntityInfoWithRegnum(
        @WebParam(name = "request", targetNamespace = "")
        LegalEntityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100302_getLegalEntityChangeInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100302_getLegalEntityChangeInfo", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100302GetLegalEntityChangeInfo")
    @ResponseWrapper(localName = "WS100302_getLegalEntityChangeInfoResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100302GetLegalEntityChangeInfoResponse")
    public ServiceResponse ws100302GetLegalEntityChangeInfo(
        @WebParam(name = "request", targetNamespace = "")
        EntityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100316_legalEntityOpenData")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100316_legalEntityOpenData", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100316LegalEntityOpenData")
    @ResponseWrapper(localName = "WS100316_legalEntityOpenDataResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100316LegalEntityOpenDataResponse")
    public ServiceResponse ws100316LegalEntityOpenData(
        @WebParam(name = "request", targetNamespace = "")
        LegalEntityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100309_legalEntityWasCriminalLiability")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100309_legalEntityWasCriminalLiability", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100309LegalEntityWasCriminalLiability")
    @ResponseWrapper(localName = "WS100309_legalEntityWasCriminalLiabilityResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100309LegalEntityWasCriminalLiabilityResponse")
    public ServiceResponse ws100309LegalEntityWasCriminalLiability(
        @WebParam(name = "request", targetNamespace = "")
        EntityNumberData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100319_legalEntityIndustryInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100319_legalEntityIndustryInfo", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100319LegalEntityIndustryInfo")
    @ResponseWrapper(localName = "WS100319_legalEntityIndustryInfoResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100319LegalEntityIndustryInfoResponse")
    public ServiceResponse ws100319LegalEntityIndustryInfo(
        @WebParam(name = "request", targetNamespace = "")
        NonLegalEntityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100318_legalEntityOfficialNamesInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100318_legalEntityOfficialNamesInfo", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100318LegalEntityOfficialNamesInfo")
    @ResponseWrapper(localName = "WS100318_legalEntityOfficialNamesInfoResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100318LegalEntityOfficialNamesInfoResponse")
    public ServiceResponse ws100318LegalEntityOfficialNamesInfo(
        @WebParam(name = "request", targetNamespace = "")
        NonLegalEntityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100315_checkLegalEntityDirector")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100315_checkLegalEntityDirector", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100315CheckLegalEntityDirector")
    @ResponseWrapper(localName = "WS100315_checkLegalEntityDirectorResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100315CheckLegalEntityDirectorResponse")
    public ServiceResponse ws100315CheckLegalEntityDirector(
        @WebParam(name = "request", targetNamespace = "")
        LegalEntityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100301_getLegalEntityInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100301_getLegalEntityInfo", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100301GetLegalEntityInfo")
    @ResponseWrapper(localName = "WS100301_getLegalEntityInfoResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100301GetLegalEntityInfoResponse")
    public ServiceResponse ws100301GetLegalEntityInfo(
        @WebParam(name = "request", targetNamespace = "")
        EntityNumberData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100308_legalEntityDoingCriminalLiability")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100308_legalEntityDoingCriminalLiability", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100308LegalEntityDoingCriminalLiability")
    @ResponseWrapper(localName = "WS100308_legalEntityDoingCriminalLiabilityResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100308LegalEntityDoingCriminalLiabilityResponse")
    public ServiceResponse ws100308LegalEntityDoingCriminalLiability(
        @WebParam(name = "request", targetNamespace = "")
        EntityNumberData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100303_getLegalEntityLiquidationInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100303_getLegalEntityLiquidationInfo", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100303GetLegalEntityLiquidationInfo")
    @ResponseWrapper(localName = "WS100303_getLegalEntityLiquidationInfoResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100303GetLegalEntityLiquidationInfoResponse")
    public ServiceResponse ws100303GetLegalEntityLiquidationInfo(
        @WebParam(name = "request", targetNamespace = "")
        EntityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100327_getCustomsOffnsInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100327_getCustomsOffnsInfo", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100327GetCustomsOffnsInfo")
    @ResponseWrapper(localName = "WS100327_getCustomsOffnsInfoResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100327GetCustomsOffnsInfoResponse")
    public ServiceResponse ws100327GetCustomsOffnsInfo(
        @WebParam(name = "request", targetNamespace = "")
        GetCustomsOffnsRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypLegalEntity.ServiceResponse
     */
    @WebMethod(operationName = "WS100321_getCustomsInqInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100321_getCustomsInqInfo", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100321GetCustomsInqInfo")
    @ResponseWrapper(localName = "WS100321_getCustomsInqInfoResponse", targetNamespace = "http://les.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypLegalEntity.WS100321GetCustomsInqInfoResponse")
    public ServiceResponse ws100321GetCustomsInqInfo(
        @WebParam(name = "request", targetNamespace = "")
        GetCustomsInqRequestData request);

}
