
package mn.gov.ema.emongolia.data.XypLegalEntity;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LesServiceService", targetNamespace = "http://les.xyp.gov.mn/", wsdlLocation = "https://xyp.gov.mn/legal-entity-1.5.0/ws?WSDL")
public class LesServiceService
    extends Service
{

    private final static URL LESSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException LESSERVICESERVICE_EXCEPTION;
    private final static QName LESSERVICESERVICE_QNAME = new QName("http://les.xyp.gov.mn/", "LesServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://xyp.gov.mn/legal-entity-1.5.0/ws?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LESSERVICESERVICE_WSDL_LOCATION = url;
        LESSERVICESERVICE_EXCEPTION = e;
    }

    public LesServiceService() {
        super(__getWsdlLocation(), LESSERVICESERVICE_QNAME);
    }

    public LesServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LESSERVICESERVICE_QNAME, features);
    }

    public LesServiceService(URL wsdlLocation) {
        super(wsdlLocation, LESSERVICESERVICE_QNAME);
    }

    public LesServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LESSERVICESERVICE_QNAME, features);
    }

    public LesServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LesServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LesService
     */
    @WebEndpoint(name = "LesServicePort")
    public LesService getLesServicePort() {
        return super.getPort(new QName("http://les.xyp.gov.mn/", "LesServicePort"), LesService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LesService
     */
    @WebEndpoint(name = "LesServicePort")
    public LesService getLesServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://les.xyp.gov.mn/", "LesServicePort"), LesService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LESSERVICESERVICE_EXCEPTION!= null) {
            throw LESSERVICESERVICE_EXCEPTION;
        }
        return LESSERVICESERVICE_WSDL_LOCATION;
    }

}
