
package mn.gov.ema.emongolia.data.XypProperty;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PropertyServiceService", targetNamespace = "http://property.xyp.gov.mn/", wsdlLocation = "https://xyp.gov.mn/property-1.5.0/ws?WSDL")
public class PropertyServiceService
    extends Service
{

    private final static URL PROPERTYSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PROPERTYSERVICESERVICE_EXCEPTION;
    private final static QName PROPERTYSERVICESERVICE_QNAME = new QName("http://property.xyp.gov.mn/", "PropertyServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://xyp.gov.mn/property-1.5.0/ws?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROPERTYSERVICESERVICE_WSDL_LOCATION = url;
        PROPERTYSERVICESERVICE_EXCEPTION = e;
    }

    public PropertyServiceService() {
        super(__getWsdlLocation(), PROPERTYSERVICESERVICE_QNAME);
    }

    public PropertyServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROPERTYSERVICESERVICE_QNAME, features);
    }

    public PropertyServiceService(URL wsdlLocation) {
        super(wsdlLocation, PROPERTYSERVICESERVICE_QNAME);
    }

    public PropertyServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROPERTYSERVICESERVICE_QNAME, features);
    }

    public PropertyServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PropertyServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PropertyService
     */
    @WebEndpoint(name = "PropertyServicePort")
    public PropertyService getPropertyServicePort() {
        return super.getPort(new QName("http://property.xyp.gov.mn/", "PropertyServicePort"), PropertyService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PropertyService
     */
    @WebEndpoint(name = "PropertyServicePort")
    public PropertyService getPropertyServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://property.xyp.gov.mn/", "PropertyServicePort"), PropertyService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROPERTYSERVICESERVICE_EXCEPTION!= null) {
            throw PROPERTYSERVICESERVICE_EXCEPTION;
        }
        return PROPERTYSERVICESERVICE_WSDL_LOCATION;
    }

}
