
package mn.gov.ema.emongolia.data.XypInsurance;

import mn.gov.ema.emongolia.data.ServiceResponse.ServiceResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InsuranceService", targetNamespace = "http://insurance.xyp.gov.mn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InsuranceService {


    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100504_confirmAppUser")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100504_confirmAppUser", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100504ConfirmAppUser")
    @ResponseWrapper(localName = "WS100504_confirmAppUserResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100504ConfirmAppUserResponse")
    public ServiceResponse ws100504ConfirmAppUser(
        @WebParam(name = "request", targetNamespace = "")
        ServiceConfirmAppUserRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100569_disabilityPensionDocumentEngInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100569_disabilityPensionDocumentEngInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100569DisabilityPensionDocumentEngInfo")
    @ResponseWrapper(localName = "WS100569_disabilityPensionDocumentEngInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100569DisabilityPensionDocumentEngInfoResponse")
    public ServiceResponse ws100569DisabilityPensionDocumentEngInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckIsInsuredRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100522_checkHouseHoldSC")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100522_checkHouseHoldSC", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100522CheckHouseHoldSC")
    @ResponseWrapper(localName = "WS100522_checkHouseHoldSCResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100522CheckHouseHoldSCResponse")
    public ServiceResponse ws100522CheckHouseHoldSC(
        @WebParam(name = "request", targetNamespace = "")
        CheckMotherTimeRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100542_socialInsuranceInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100542_socialInsuranceInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100542SocialInsuranceInfo")
    @ResponseWrapper(localName = "WS100542_socialInsuranceInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100542SocialInsuranceInfoResponse")
    public ServiceResponse ws100542SocialInsuranceInfo(
        @WebParam(name = "request", targetNamespace = "")
        InsuranceRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100537_pregnancyChildbirthInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100537_pregnancyChildbirthInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100537PregnancyChildbirthInfo")
    @ResponseWrapper(localName = "WS100537_pregnancyChildbirthInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100537PregnancyChildbirthInfoResponse")
    public ServiceResponse ws100537PregnancyChildbirthInfo(
        @WebParam(name = "request", targetNamespace = "")
        PregnancyChildbirthInfoRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100550_pregnancyChildbirthCertList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100550_pregnancyChildbirthCertList", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100550PregnancyChildbirthCertList")
    @ResponseWrapper(localName = "WS100550_pregnancyChildbirthCertListResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100550PregnancyChildbirthCertListResponse")
    public ServiceResponse ws100550PregnancyChildbirthCertList(
        @WebParam(name = "request", targetNamespace = "")
        WorkHistoryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100507_getInsureeWorkHistoryInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100507_getInsureeWorkHistoryInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100507GetInsureeWorkHistoryInfo")
    @ResponseWrapper(localName = "WS100507_getInsureeWorkHistoryInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100507GetInsureeWorkHistoryInfoResponse")
    public ServiceResponse ws100507GetInsureeWorkHistoryInfo(
        @WebParam(name = "request", targetNamespace = "")
        WorkHistoryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100516_getInsuredForLastThreeMonthInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100516_getInsuredForLastThreeMonthInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100516GetInsuredForLastThreeMonthInfo")
    @ResponseWrapper(localName = "WS100516_getInsuredForLastThreeMonthInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100516GetInsuredForLastThreeMonthInfoResponse")
    public ServiceResponse ws100516GetInsuredForLastThreeMonthInfo(
        @WebParam(name = "request", targetNamespace = "")
        WorkHistoryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100535_findOrganizationForMedicalCert")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100535_findOrganizationForMedicalCert", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100535FindOrganizationForMedicalCert")
    @ResponseWrapper(localName = "WS100535_findOrganizationForMedicalCertResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100535FindOrganizationForMedicalCertResponse")
    public ServiceResponse ws100535FindOrganizationForMedicalCert(
        @WebParam(name = "request", targetNamespace = "")
        FindOrganizationRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100501_getCitizenSalaryInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100501_getCitizenSalaryInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100501GetCitizenSalaryInfo")
    @ResponseWrapper(localName = "WS100501_getCitizenSalaryInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100501GetCitizenSalaryInfoResponse")
    public ServiceResponse ws100501GetCitizenSalaryInfo(
        @WebParam(name = "request", targetNamespace = "")
        InsuranceCitizenRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100555_getBankList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100555_getBankList", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100555GetBankList")
    @ResponseWrapper(localName = "WS100555_getBankListResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100555GetBankListResponse")
    public ServiceResponse ws100555GetBankList(
        @WebParam(name = "request", targetNamespace = "")
        WorkHistoryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100505_createAppUser")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100505_createAppUser", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100505CreateAppUser")
    @ResponseWrapper(localName = "WS100505_createAppUserResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100505CreateAppUserResponse")
    public ServiceResponse ws100505CreateAppUser(
        @WebParam(name = "request", targetNamespace = "")
        ServiceCreateAppUserRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100551_pregnancyBenefitsApply")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100551_pregnancyBenefitsApply", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100551PregnancyBenefitsApply")
    @ResponseWrapper(localName = "WS100551_pregnancyBenefitsApplyResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100551PregnancyBenefitsApplyResponse")
    public ServiceResponse ws100551PregnancyBenefitsApply(
        @WebParam(name = "request", targetNamespace = "")
        PregnancyBenefitsApplyRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100556_getHealthInsuranceFee")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100556_getHealthInsuranceFee", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100556GetHealthInsuranceFee")
    @ResponseWrapper(localName = "WS100556_getHealthInsuranceFeeResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100556GetHealthInsuranceFeeResponse")
    public ServiceResponse ws100556GetHealthInsuranceFee(
        @WebParam(name = "request", targetNamespace = "")
        CheckIsInsuredRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100518_getPensionInformationData")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100518_getPensionInformationData", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100518GetPensionInformationData")
    @ResponseWrapper(localName = "WS100518_getPensionInformationDataResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100518GetPensionInformationDataResponse")
    public ServiceResponse ws100518GetPensionInformationData(
        @WebParam(name = "request", targetNamespace = "")
        CheckMotherTimeRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100502_getCitizenPensionInquiry")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100502_getCitizenPensionInquiry", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100502GetCitizenPensionInquiry")
    @ResponseWrapper(localName = "WS100502_getCitizenPensionInquiryResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100502GetCitizenPensionInquiryResponse")
    public ServiceResponse ws100502GetCitizenPensionInquiry(
        @WebParam(name = "request", targetNamespace = "")
        InsuranceCitizenRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100552_unemploymentBenefitsList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100552_unemploymentBenefitsList", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100552UnemploymentBenefitsList")
    @ResponseWrapper(localName = "WS100552_unemploymentBenefitsListResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100552UnemploymentBenefitsListResponse")
    public ServiceResponse ws100552UnemploymentBenefitsList(
        @WebParam(name = "request", targetNamespace = "")
        WorkHistoryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100506_findAppUser")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100506_findAppUser", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100506FindAppUser")
    @ResponseWrapper(localName = "WS100506_findAppUserResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100506FindAppUserResponse")
    public ServiceResponse ws100506FindAppUser(
        @WebParam(name = "request", targetNamespace = "")
        ServiceFindAppUserRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100510_getSiWorkerAccountInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100510_getSiWorkerAccountInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100510GetSiWorkerAccountInfo")
    @ResponseWrapper(localName = "WS100510_getSiWorkerAccountInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100510GetSiWorkerAccountInfoResponse")
    public ServiceResponse ws100510GetSiWorkerAccountInfo(
        @WebParam(name = "request", targetNamespace = "")
        WorkHistoryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100523_getCampVoucherOfElderInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100523_getCampVoucherOfElderInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100523GetCampVoucherOfElderInfo")
    @ResponseWrapper(localName = "WS100523_getCampVoucherOfElderInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100523GetCampVoucherOfElderInfoResponse")
    public ServiceResponse ws100523GetCampVoucherOfElderInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckMotherTimeRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100531_checkPensionDate")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100531_checkPensionDate", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100531CheckPensionDate")
    @ResponseWrapper(localName = "WS100531_checkPensionDateResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100531CheckPensionDateResponse")
    public ServiceResponse ws100531CheckPensionDate(
        @WebParam(name = "request", targetNamespace = "")
        CheckPensionDateRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100567_lostCaregiverPensionDocumentInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100567_lostCaregiverPensionDocumentInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100567LostCaregiverPensionDocumentInfo")
    @ResponseWrapper(localName = "WS100567_lostCaregiverPensionDocumentInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100567LostCaregiverPensionDocumentInfoResponse")
    public ServiceResponse ws100567LostCaregiverPensionDocumentInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckIsInsuredRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100549_disabilityBenefitsApply")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100549_disabilityBenefitsApply", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100549DisabilityBenefitsApply")
    @ResponseWrapper(localName = "WS100549_disabilityBenefitsApplyResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100549DisabilityBenefitsApplyResponse")
    public ServiceResponse ws100549DisabilityBenefitsApply(
        @WebParam(name = "request", targetNamespace = "")
        DisabilityBenefitsApplyRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100512_checkIsInsuredInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100512_checkIsInsuredInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100512CheckIsInsuredInfo")
    @ResponseWrapper(localName = "WS100512_checkIsInsuredInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100512CheckIsInsuredInfoResponse")
    public ServiceResponse ws100512CheckIsInsuredInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckIsInsuredRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100532_citizenLossOfAbilityToWorkInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100532_citizenLossOfAbilityToWorkInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100532CitizenLossOfAbilityToWorkInfo")
    @ResponseWrapper(localName = "WS100532_citizenLossOfAbilityToWorkInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100532CitizenLossOfAbilityToWorkInfoResponse")
    public ServiceResponse ws100532CitizenLossOfAbilityToWorkInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckPensionDateRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100564_pensionDocumentInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100564_pensionDocumentInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100564PensionDocumentInfo")
    @ResponseWrapper(localName = "WS100564_pensionDocumentInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100564PensionDocumentInfoResponse")
    public ServiceResponse ws100564PensionDocumentInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckIsInsuredRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100526_reportLog")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100526_reportLog", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100526ReportLog")
    @ResponseWrapper(localName = "WS100526_reportLogResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100526ReportLogResponse")
    public ServiceResponse ws100526ReportLog(
        @WebParam(name = "request", targetNamespace = "")
        ReportLogRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100509_getSalaryFoundByIndutyInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100509_getSalaryFoundByIndutyInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100509GetSalaryFoundByIndutyInfo")
    @ResponseWrapper(localName = "WS100509_getSalaryFoundByIndutyInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100509GetSalaryFoundByIndutyInfoResponse")
    public ServiceResponse ws100509GetSalaryFoundByIndutyInfo(
        @WebParam(name = "request", targetNamespace = "")
        SalaryFoundByOccupationRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100527_getPaymentInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100527_getPaymentInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100527GetPaymentInfo")
    @ResponseWrapper(localName = "WS100527_getPaymentInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100527GetPaymentInfoResponse")
    public ServiceResponse ws100527GetPaymentInfo(
        @WebParam(name = "request", targetNamespace = "")
        PaymentRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100545_medicalCertCheck")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100545_medicalCertCheck", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100545MedicalCertCheck")
    @ResponseWrapper(localName = "WS100545_medicalCertCheckResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100545MedicalCertCheckResponse")
    public ServiceResponse ws100545MedicalCertCheck(
        @WebParam(name = "request", targetNamespace = "")
        MedicalCertCheckRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100539_pregnancyChildbirthCertInvalid")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100539_pregnancyChildbirthCertInvalid", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100539PregnancyChildbirthCertInvalid")
    @ResponseWrapper(localName = "WS100539_pregnancyChildbirthCertInvalidResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100539PregnancyChildbirthCertInvalidResponse")
    public ServiceResponse ws100539PregnancyChildbirthCertInvalid(
        @WebParam(name = "request", targetNamespace = "")
        MedicalCertInvalidRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100563_funeralAllowanceInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100563_funeralAllowanceInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100563FuneralAllowanceInfo")
    @ResponseWrapper(localName = "WS100563_funeralAllowanceInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100563FuneralAllowanceInfoResponse")
    public ServiceResponse ws100563FuneralAllowanceInfo(
        @WebParam(name = "request", targetNamespace = "")
        WorkHistoryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100513_findOrganizationInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100513_findOrganizationInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100513FindOrganizationInfo")
    @ResponseWrapper(localName = "WS100513_findOrganizationInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100513FindOrganizationInfoResponse")
    public ServiceResponse ws100513FindOrganizationInfo(
        @WebParam(name = "request", targetNamespace = "")
        FindOrganizationRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100521_checkHouseHoldFood")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100521_checkHouseHoldFood", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100521CheckHouseHoldFood")
    @ResponseWrapper(localName = "WS100521_checkHouseHoldFoodResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100521CheckHouseHoldFoodResponse")
    public ServiceResponse ws100521CheckHouseHoldFood(
        @WebParam(name = "request", targetNamespace = "")
        CheckMotherTimeRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100520_checkHouseHoldChild")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100520_checkHouseHoldChild", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100520CheckHouseHoldChild")
    @ResponseWrapper(localName = "WS100520_checkHouseHoldChildResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100520CheckHouseHoldChildResponse")
    public ServiceResponse ws100520CheckHouseHoldChild(
        @WebParam(name = "request", targetNamespace = "")
        CheckMotherTimeRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100517_checkMotherTimeAllInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100517_checkMotherTimeAllInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100517CheckMotherTimeAllInfo")
    @ResponseWrapper(localName = "WS100517_checkMotherTimeAllInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100517CheckMotherTimeAllInfoResponse")
    public ServiceResponse ws100517CheckMotherTimeAllInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckMotherTimeAllRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100566_disabilityPensionDocumentInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100566_disabilityPensionDocumentInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100566DisabilityPensionDocumentInfo")
    @ResponseWrapper(localName = "WS100566_disabilityPensionDocumentInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100566DisabilityPensionDocumentInfoResponse")
    public ServiceResponse ws100566DisabilityPensionDocumentInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckIsInsuredRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100503_getCheckMotherTimeInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100503_getCheckMotherTimeInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100503GetCheckMotherTimeInfo")
    @ResponseWrapper(localName = "WS100503_getCheckMotherTimeInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100503GetCheckMotherTimeInfoResponse")
    public ServiceResponse ws100503GetCheckMotherTimeInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckMotherTimeRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100533_insuredListLast3MonthByDate")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100533_insuredListLast3MonthByDate", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100533InsuredListLast3MonthByDate")
    @ResponseWrapper(localName = "WS100533_insuredListLast3MonthByDateResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100533InsuredListLast3MonthByDateResponse")
    public ServiceResponse ws100533InsuredListLast3MonthByDate(
        @WebParam(name = "request", targetNamespace = "")
        WorkHistoryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100525_getOrganizationDeptInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100525_getOrganizationDeptInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100525GetOrganizationDeptInfo")
    @ResponseWrapper(localName = "WS100525_getOrganizationDeptInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100525GetOrganizationDeptInfoResponse")
    public ServiceResponse ws100525GetOrganizationDeptInfo(
        @WebParam(name = "request", targetNamespace = "")
        ServiceOrganizationDeptRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100546_disabilityMedicalCertEdit")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100546_disabilityMedicalCertEdit", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100546DisabilityMedicalCertEdit")
    @ResponseWrapper(localName = "WS100546_disabilityMedicalCertEditResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100546DisabilityMedicalCertEditResponse")
    public ServiceResponse ws100546DisabilityMedicalCertEdit(
        @WebParam(name = "request", targetNamespace = "")
        DisabilityMedicalCertEditRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100554_unemploymentBenefitsCount")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100554_unemploymentBenefitsCount", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100554UnemploymentBenefitsCount")
    @ResponseWrapper(localName = "WS100554_unemploymentBenefitsCountResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100554UnemploymentBenefitsCountResponse")
    public ServiceResponse ws100554UnemploymentBenefitsCount(
        @WebParam(name = "request", targetNamespace = "")
        WorkHistoryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100560_refundHalfAccountList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100560_refundHalfAccountList", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100560RefundHalfAccountList")
    @ResponseWrapper(localName = "WS100560_refundHalfAccountListResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100560RefundHalfAccountListResponse")
    public ServiceResponse ws100560RefundHalfAccountList(
        @WebParam(name = "request", targetNamespace = "")
        WorkHistoryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100514_getEmployerNumWithDeptInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100514_getEmployerNumWithDeptInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100514GetEmployerNumWithDeptInfo")
    @ResponseWrapper(localName = "WS100514_getEmployerNumWithDeptInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100514GetEmployerNumWithDeptInfoResponse")
    public ServiceResponse ws100514GetEmployerNumWithDeptInfo(
        @WebParam(name = "request", targetNamespace = "")
        GetEmployerNumWithDeptRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100534_organizationInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100534_organizationInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100534OrganizationInfo")
    @ResponseWrapper(localName = "WS100534_organizationInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100534OrganizationInfoResponse")
    public ServiceResponse ws100534OrganizationInfo(
        @WebParam(name = "request", targetNamespace = "")
        ServiceOrganizationDeptRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100540_disabilityMedicalCertInvalid")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100540_disabilityMedicalCertInvalid", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100540DisabilityMedicalCertInvalid")
    @ResponseWrapper(localName = "WS100540_disabilityMedicalCertInvalidResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100540DisabilityMedicalCertInvalidResponse")
    public ServiceResponse ws100540DisabilityMedicalCertInvalid(
        @WebParam(name = "request", targetNamespace = "")
        MedicalCertInvalidRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100538_disabilityMedicalCertInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100538_disabilityMedicalCertInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100538DisabilityMedicalCertInfo")
    @ResponseWrapper(localName = "WS100538_disabilityMedicalCertInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100538DisabilityMedicalCertInfoResponse")
    public ServiceResponse ws100538DisabilityMedicalCertInfo(
        @WebParam(name = "request", targetNamespace = "")
        DisabilityMedicalCertRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100559_refundHalfBankList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100559_refundHalfBankList", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100559RefundHalfBankList")
    @ResponseWrapper(localName = "WS100559_refundHalfBankListResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100559RefundHalfBankListResponse")
    public ServiceResponse ws100559RefundHalfBankList(
        @WebParam(name = "request", targetNamespace = "")
        WorkHistoryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100543_retirementListInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100543_retirementListInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100543RetirementListInfo")
    @ResponseWrapper(localName = "WS100543_retirementListInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100543RetirementListInfoResponse")
    public ServiceResponse ws100543RetirementListInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckPensionDateRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100524_getDisabledPersonSupplyInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100524_getDisabledPersonSupplyInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100524GetDisabledPersonSupplyInfo")
    @ResponseWrapper(localName = "WS100524_getDisabledPersonSupplyInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100524GetDisabledPersonSupplyInfoResponse")
    public ServiceResponse ws100524GetDisabledPersonSupplyInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckMotherTimeRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100557_citizenInsuranceInfoForStatistic")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100557_citizenInsuranceInfoForStatistic", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100557CitizenInsuranceInfoForStatistic")
    @ResponseWrapper(localName = "WS100557_citizenInsuranceInfoForStatisticResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100557CitizenInsuranceInfoForStatisticResponse")
    public ServiceResponse ws100557CitizenInsuranceInfoForStatistic(
        @WebParam(name = "request", targetNamespace = "")
        CitizenInsuranceInfoForStatRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100511_getEmployerInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100511_getEmployerInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100511GetEmployerInfo")
    @ResponseWrapper(localName = "WS100511_getEmployerInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100511GetEmployerInfoResponse")
    public ServiceResponse ws100511GetEmployerInfo(
        @WebParam(name = "request", targetNamespace = "")
        EmployerRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100515_foreignEmployerInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100515_foreignEmployerInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100515ForeignEmployerInfo")
    @ResponseWrapper(localName = "WS100515_foreignEmployerInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100515ForeignEmployerInfoResponse")
    public ServiceResponse ws100515ForeignEmployerInfo(
        @WebParam(name = "request", targetNamespace = "")
        GetEmployerNumWithDeptRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100508_getSalaryFoundByOccupationInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100508_getSalaryFoundByOccupationInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100508GetSalaryFoundByOccupationInfo")
    @ResponseWrapper(localName = "WS100508_getSalaryFoundByOccupationInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100508GetSalaryFoundByOccupationInfoResponse")
    public ServiceResponse ws100508GetSalaryFoundByOccupationInfo(
        @WebParam(name = "request", targetNamespace = "")
        SalaryFoundByOccupationRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100561_refundHalfCreateAccount")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100561_refundHalfCreateAccount", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100561RefundHalfCreateAccount")
    @ResponseWrapper(localName = "WS100561_refundHalfCreateAccountResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100561RefundHalfCreateAccountResponse")
    public ServiceResponse ws100561RefundHalfCreateAccount(
        @WebParam(name = "request", targetNamespace = "")
        RefundHalfAccountRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100530_organizationEmployeeInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100530_organizationEmployeeInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100530OrganizationEmployeeInfo")
    @ResponseWrapper(localName = "WS100530_organizationEmployeeInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100530OrganizationEmployeeInfoResponse")
    public ServiceResponse ws100530OrganizationEmployeeInfo(
        @WebParam(name = "request", targetNamespace = "")
        OrganizationEmployeeRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100544_getInsuredForLastThreeMonthOccupationInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100544_getInsuredForLastThreeMonthOccupationInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100544GetInsuredForLastThreeMonthOccupationInfo")
    @ResponseWrapper(localName = "WS100544_getInsuredForLastThreeMonthOccupationInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100544GetInsuredForLastThreeMonthOccupationInfoResponse")
    public ServiceResponse ws100544GetInsuredForLastThreeMonthOccupationInfo(
        @WebParam(name = "request", targetNamespace = "")
        WorkHistoryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100547_pregnancyChildbirthEdit")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100547_pregnancyChildbirthEdit", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100547PregnancyChildbirthEdit")
    @ResponseWrapper(localName = "WS100547_pregnancyChildbirthEditResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100547PregnancyChildbirthEditResponse")
    public ServiceResponse ws100547PregnancyChildbirthEdit(
        @WebParam(name = "request", targetNamespace = "")
        PregnancyChildbirthEditRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100529_getSalaryFeeList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100529_getSalaryFeeList", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100529GetSalaryFeeList")
    @ResponseWrapper(localName = "WS100529_getSalaryFeeListResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100529GetSalaryFeeListResponse")
    public ServiceResponse ws100529GetSalaryFeeList(
        @WebParam(name = "request", targetNamespace = "")
        GetSalaryFeeRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100562_refundHalfUpdateAccount")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100562_refundHalfUpdateAccount", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100562RefundHalfUpdateAccount")
    @ResponseWrapper(localName = "WS100562_refundHalfUpdateAccountResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100562RefundHalfUpdateAccountResponse")
    public ServiceResponse ws100562RefundHalfUpdateAccount(
        @WebParam(name = "request", targetNamespace = "")
        RefundHalfAccountRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100528_paymentLog")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100528_paymentLog", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100528PaymentLog")
    @ResponseWrapper(localName = "WS100528_paymentLogResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100528PaymentLogResponse")
    public ServiceResponse ws100528PaymentLog(
        @WebParam(name = "request", targetNamespace = "")
        PaymentLogRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100541_healthInsuranceInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100541_healthInsuranceInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100541HealthInsuranceInfo")
    @ResponseWrapper(localName = "WS100541_healthInsuranceInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100541HealthInsuranceInfoResponse")
    public ServiceResponse ws100541HealthInsuranceInfo(
        @WebParam(name = "request", targetNamespace = "")
        InsuranceRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100519_checkChildMoney")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100519_checkChildMoney", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100519CheckChildMoney")
    @ResponseWrapper(localName = "WS100519_checkChildMoneyResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100519CheckChildMoneyResponse")
    public ServiceResponse ws100519CheckChildMoney(
        @WebParam(name = "request", targetNamespace = "")
        CheckMotherTimeRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100536_checkMotherEmployed")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100536_checkMotherEmployed", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100536CheckMotherEmployed")
    @ResponseWrapper(localName = "WS100536_checkMotherEmployedResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100536CheckMotherEmployedResponse")
    public ServiceResponse ws100536CheckMotherEmployed(
        @WebParam(name = "request", targetNamespace = "")
        CheckIsInsuredRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100568_pensionDocumentEngInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100568_pensionDocumentEngInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100568PensionDocumentEngInfo")
    @ResponseWrapper(localName = "WS100568_pensionDocumentEngInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100568PensionDocumentEngInfoResponse")
    public ServiceResponse ws100568PensionDocumentEngInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckIsInsuredRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100548_disabilityMedicalCertList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100548_disabilityMedicalCertList", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100548DisabilityMedicalCertList")
    @ResponseWrapper(localName = "WS100548_disabilityMedicalCertListResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100548DisabilityMedicalCertListResponse")
    public ServiceResponse ws100548DisabilityMedicalCertList(
        @WebParam(name = "request", targetNamespace = "")
        WorkHistoryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100553_unemploymentBenefitsApply")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100553_unemploymentBenefitsApply", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100553UnemploymentBenefitsApply")
    @ResponseWrapper(localName = "WS100553_unemploymentBenefitsApplyResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100553UnemploymentBenefitsApplyResponse")
    public ServiceResponse ws100553UnemploymentBenefitsApply(
        @WebParam(name = "request", targetNamespace = "")
        UnemploymentBenefitsApplyRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100558_orgInfoForStatistic")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100558_orgInfoForStatistic", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100558OrgInfoForStatistic")
    @ResponseWrapper(localName = "WS100558_orgInfoForStatisticResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100558OrgInfoForStatisticResponse")
    public ServiceResponse ws100558OrgInfoForStatistic(
        @WebParam(name = "request", targetNamespace = "")
        OrgInfoForStatisticRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100570_lostCaregiverPensionDocumentEngInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100570_lostCaregiverPensionDocumentEngInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100570LostCaregiverPensionDocumentEngInfo")
    @ResponseWrapper(localName = "WS100570_lostCaregiverPensionDocumentEngInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100570LostCaregiverPensionDocumentEngInfoResponse")
    public ServiceResponse ws100570LostCaregiverPensionDocumentEngInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckIsInsuredRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypInsurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100565_getCitizenSalaryInfoEng")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100565_getCitizenSalaryInfoEng", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100565GetCitizenSalaryInfoEng")
    @ResponseWrapper(localName = "WS100565_getCitizenSalaryInfoEngResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypInsurance.WS100565GetCitizenSalaryInfoEngResponse")
    public ServiceResponse ws100565GetCitizenSalaryInfoEng(
        @WebParam(name = "request", targetNamespace = "")
        InsuranceCitizenRequestData request);

}
