
package mn.gov.ema.emongolia.data.XypGovernment;

import mn.gov.ema.emongolia.data.ServiceResponse.ServiceResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GovernmentService", targetNamespace = "http://government.xyp.gov.mn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GovernmentService {


    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10007_legalEntityOwnerInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10007_legalEntityOwnerInfo", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10007LegalEntityOwnerInfo")
    @ResponseWrapper(localName = "GS10007_legalEntityOwnerInfoResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10007LegalEntityOwnerInfoResponse")
    public ServiceResponse gs10007LegalEntityOwnerInfo(
        @WebParam(name = "request", targetNamespace = "")
        LegalEntityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10015_citizenIDCardFirstTimeInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10015_citizenIDCardFirstTimeInfo", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10015CitizenIDCardFirstTimeInfo")
    @ResponseWrapper(localName = "GS10015_citizenIDCardFirstTimeInfoResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10015CitizenIDCardFirstTimeInfoResponse")
    public ServiceResponse gs10015CitizenIDCardFirstTimeInfo(
        @WebParam(name = "request", targetNamespace = "")
        LegalEntityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10028_citizenNonPaymentEngInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10028_citizenNonPaymentEngInfo", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10028CitizenNonPaymentEngInfo")
    @ResponseWrapper(localName = "GS10028_citizenNonPaymentEngInfoResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10028CitizenNonPaymentEngInfoResponse")
    public ServiceResponse gs10028CitizenNonPaymentEngInfo(
        @WebParam(name = "request", targetNamespace = "")
        CovidVaccineDoseCountRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10004_legalEntityClosuresInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10004_legalEntityClosuresInfo", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10004LegalEntityClosuresInfo")
    @ResponseWrapper(localName = "GS10004_legalEntityClosuresInfoResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10004LegalEntityClosuresInfoResponse")
    public ServiceResponse gs10004LegalEntityClosuresInfo(
        @WebParam(name = "request", targetNamespace = "")
        LegalEntityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10029_citizenNoMarriageInfoData")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10029_citizenNoMarriageInfoData", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10029CitizenNoMarriageInfoData")
    @ResponseWrapper(localName = "GS10029_citizenNoMarriageInfoDataResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10029CitizenNoMarriageInfoDataResponse")
    public ServiceResponse gs10029CitizenNoMarriageInfoData(
        @WebParam(name = "request", targetNamespace = "")
        CitizenIDCardInfoEngRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10031_ssoPhoneCheck")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10031_ssoPhoneCheck", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10031SsoPhoneCheck")
    @ResponseWrapper(localName = "GS10031_ssoPhoneCheckResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10031SsoPhoneCheckResponse")
    public ServiceResponse gs10031SsoPhoneCheck(
        @WebParam(name = "request", targetNamespace = "")
        SsoPhoneCheckRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10025_notaryTrustArchivedInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10025_notaryTrustArchivedInfo", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10025NotaryTrustArchivedInfo")
    @ResponseWrapper(localName = "GS10025_notaryTrustArchivedInfoResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10025NotaryTrustArchivedInfoResponse")
    public ServiceResponse gs10025NotaryTrustArchivedInfo(
        @WebParam(name = "request", targetNamespace = "")
        NotaryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10021_covidVaccineDoseCount")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10021_covidVaccineDoseCount", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10021CovidVaccineDoseCount")
    @ResponseWrapper(localName = "GS10021_covidVaccineDoseCountResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10021CovidVaccineDoseCountResponse")
    public ServiceResponse gs10021CovidVaccineDoseCount(
        @WebParam(name = "request", targetNamespace = "")
        CovidVaccineDoseCountRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10001_citizenDiagnosisInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10001_citizenDiagnosisInfo", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10001CitizenDiagnosisInfo")
    @ResponseWrapper(localName = "GS10001_citizenDiagnosisInfoResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10001CitizenDiagnosisInfoResponse")
    public ServiceResponse gs10001CitizenDiagnosisInfo(
        @WebParam(name = "request", targetNamespace = "")
        CitizenDiagnosysRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10002_citizenCovid19EPass")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10002_citizenCovid19EPass", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10002CitizenCovid19EPass")
    @ResponseWrapper(localName = "GS10002_citizenCovid19EPassResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10002CitizenCovid19EPassResponse")
    public ServiceResponse gs10002CitizenCovid19EPass(
        @WebParam(name = "request", targetNamespace = "")
        CitizenCovid19EPassRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10006_legalEntityIndustryInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10006_legalEntityIndustryInfo", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10006LegalEntityIndustryInfo")
    @ResponseWrapper(localName = "GS10006_legalEntityIndustryInfoResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10006LegalEntityIndustryInfoResponse")
    public ServiceResponse gs10006LegalEntityIndustryInfo(
        @WebParam(name = "request", targetNamespace = "")
        LegalEntityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10019_firearmOwnerCertificateInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10019_firearmOwnerCertificateInfo", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10019FirearmOwnerCertificateInfo")
    @ResponseWrapper(localName = "GS10019_firearmOwnerCertificateInfoResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10019FirearmOwnerCertificateInfoResponse")
    public ServiceResponse gs10019FirearmOwnerCertificateInfo(
        @WebParam(name = "request", targetNamespace = "")
        FirearmOwnerCertificateRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10012_citizenAddressArrivedInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10012_citizenAddressArrivedInfo", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10012CitizenAddressArrivedInfo")
    @ResponseWrapper(localName = "GS10012_citizenAddressArrivedInfoResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10012CitizenAddressArrivedInfoResponse")
    public ServiceResponse gs10012CitizenAddressArrivedInfo(
        @WebParam(name = "request", targetNamespace = "")
        LegalEntityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10005_legalEntityFounderInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10005_legalEntityFounderInfo", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10005LegalEntityFounderInfo")
    @ResponseWrapper(localName = "GS10005_legalEntityFounderInfoResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10005LegalEntityFounderInfoResponse")
    public ServiceResponse gs10005LegalEntityFounderInfo(
        @WebParam(name = "request", targetNamespace = "")
        LegalEntityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10017_citizenInternationalCert")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10017_citizenInternationalCert", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10017CitizenInternationalCert")
    @ResponseWrapper(localName = "GS10017_citizenInternationalCertResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10017CitizenInternationalCertResponse")
    public ServiceResponse gs10017CitizenInternationalCert(
        @WebParam(name = "request", targetNamespace = "")
        Covid19InternationalCertRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10011_childrenBirthInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10011_childrenBirthInfo", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10011ChildrenBirthInfo")
    @ResponseWrapper(localName = "GS10011_childrenBirthInfoResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10011ChildrenBirthInfoResponse")
    public ServiceResponse gs10011ChildrenBirthInfo(
        @WebParam(name = "request", targetNamespace = "")
        LegalEntityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10008_legalEntityGeneralInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10008_legalEntityGeneralInfo", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10008LegalEntityGeneralInfo")
    @ResponseWrapper(localName = "GS10008_legalEntityGeneralInfoResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10008LegalEntityGeneralInfoResponse")
    public ServiceResponse gs10008LegalEntityGeneralInfo(
        @WebParam(name = "request", targetNamespace = "")
        LegalEntityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10023_notaryTrustInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10023_notaryTrustInfo", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10023NotaryTrustInfo")
    @ResponseWrapper(localName = "GS10023_notaryTrustInfoResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10023NotaryTrustInfoResponse")
    public ServiceResponse gs10023NotaryTrustInfo(
        @WebParam(name = "request", targetNamespace = "")
        NotaryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10024_notaryVehicleInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10024_notaryVehicleInfo", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10024NotaryVehicleInfo")
    @ResponseWrapper(localName = "GS10024_notaryVehicleInfoResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10024NotaryVehicleInfoResponse")
    public ServiceResponse gs10024NotaryVehicleInfo(
        @WebParam(name = "request", targetNamespace = "")
        NotaryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10027_citizenBirthInfoEng")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10027_citizenBirthInfoEng", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10027CitizenBirthInfoEng")
    @ResponseWrapper(localName = "GS10027_citizenBirthInfoEngResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10027CitizenBirthInfoEngResponse")
    public ServiceResponse gs10027CitizenBirthInfoEng(
        @WebParam(name = "request", targetNamespace = "")
        CitizenIDCardInfoEngRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10022_studentSoldierInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10022_studentSoldierInfo", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10022StudentSoldierInfo")
    @ResponseWrapper(localName = "GS10022_studentSoldierInfoResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10022StudentSoldierInfoResponse")
    public ServiceResponse gs10022StudentSoldierInfo(
        @WebParam(name = "request", targetNamespace = "")
        StudentSoldierRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10013_citizenChangeNameInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10013_citizenChangeNameInfo", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10013CitizenChangeNameInfo")
    @ResponseWrapper(localName = "GS10013_citizenChangeNameInfoResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10013CitizenChangeNameInfoResponse")
    public ServiceResponse gs10013CitizenChangeNameInfo(
        @WebParam(name = "request", targetNamespace = "")
        LegalEntityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10026_citizenIDCardInfoEng")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10026_citizenIDCardInfoEng", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10026CitizenIDCardInfoEng")
    @ResponseWrapper(localName = "GS10026_citizenIDCardInfoEngResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10026CitizenIDCardInfoEngResponse")
    public ServiceResponse gs10026CitizenIDCardInfoEng(
        @WebParam(name = "request", targetNamespace = "")
        CitizenIDCardInfoEngRequestData request);

    /**
     * @param request
     * @return returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10030_citizenMarriageInfoEng")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10030_citizenMarriageInfoEng", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10030CitizenMarriageInfoEng")
    @ResponseWrapper(localName = "GS10030_citizenMarriageInfoEngResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10030CitizenMarriageInfoEngResponse")
    public ServiceResponse gs10030CitizenMarriageInfoEng(
        @WebParam(name = "request", targetNamespace = "")
        CitizenIDCardInfoEngRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10009_legalEntityShareHolderInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10009_legalEntityShareHolderInfo", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10009LegalEntityShareHolderInfo")
    @ResponseWrapper(localName = "GS10009_legalEntityShareHolderInfoResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10009LegalEntityShareHolderInfoResponse")
    public ServiceResponse gs10009LegalEntityShareHolderInfo(
        @WebParam(name = "request", targetNamespace = "")
        LegalEntityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10003_legalEntityBranchInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10003_legalEntityBranchInfo", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10003LegalEntityBranchInfo")
    @ResponseWrapper(localName = "GS10003_legalEntityBranchInfoResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10003LegalEntityBranchInfoResponse")
    public ServiceResponse gs10003LegalEntityBranchInfo(
        @WebParam(name = "request", targetNamespace = "")
        LegalEntityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10018_foreignCitizenInternationalCert")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10018_foreignCitizenInternationalCert", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10018ForeignCitizenInternationalCert")
    @ResponseWrapper(localName = "GS10018_foreignCitizenInternationalCertResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10018ForeignCitizenInternationalCertResponse")
    public ServiceResponse gs10018ForeignCitizenInternationalCert(
        @WebParam(name = "request", targetNamespace = "")
        ForeignCitizenInternationalCertRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10010_legalEntityStakeHolderInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10010_legalEntityStakeHolderInfo", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10010LegalEntityStakeHolderInfo")
    @ResponseWrapper(localName = "GS10010_legalEntityStakeHolderInfoResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10010LegalEntityStakeHolderInfoResponse")
    public ServiceResponse gs10010LegalEntityStakeHolderInfo(
        @WebParam(name = "request", targetNamespace = "")
        LegalEntityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10016_covid19MedicalCertificateInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10016_covid19MedicalCertificateInfo", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10016Covid19MedicalCertificateInfo")
    @ResponseWrapper(localName = "GS10016_covid19MedicalCertificateInfoResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10016Covid19MedicalCertificateInfoResponse")
    public ServiceResponse gs10016Covid19MedicalCertificateInfo(
        @WebParam(name = "request", targetNamespace = "")
        Covid19MedicalCertificateRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10014_citizenChangeRegnumInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10014_citizenChangeRegnumInfo", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10014CitizenChangeRegnumInfo")
    @ResponseWrapper(localName = "GS10014_citizenChangeRegnumInfoResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10014CitizenChangeRegnumInfoResponse")
    public ServiceResponse gs10014CitizenChangeRegnumInfo(
        @WebParam(name = "request", targetNamespace = "")
        LegalEntityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypGovernment.ServiceResponse
     */
    @WebMethod(operationName = "GS10020_nonAdultCitizenInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GS10020_nonAdultCitizenInfo", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10020NonAdultCitizenInfo")
    @ResponseWrapper(localName = "GS10020_nonAdultCitizenInfoResponse", targetNamespace = "http://government.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypGovernment.GS10020NonAdultCitizenInfoResponse")
    public ServiceResponse gs10020NonAdultCitizenInfo(
        @WebParam(name = "request", targetNamespace = "")
        NonAdultCitizenRequestData request);

}
