
package mn.gov.ema.emongolia.data.XypTransport;

import mn.gov.ema.emongolia.data.ServiceResponse.ServiceResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TransportService", targetNamespace = "http://transport.xyp.gov.mn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransportService {


    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100430_transportConflictInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100430_transportConflictInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100430TransportConflictInfo")
    @ResponseWrapper(localName = "WS100430_transportConflictInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100430TransportConflictInfoResponse")
    public ServiceResponse ws100430TransportConflictInfo(
        @WebParam(name = "request", targetNamespace = "")
        GetECDataRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100408_updatePenaltyPayment")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100408_updatePenaltyPayment", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100408UpdatePenaltyPayment")
    @ResponseWrapper(localName = "WS100408_updatePenaltyPaymentResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100408UpdatePenaltyPaymentResponse")
    public ServiceResponse ws100408UpdatePenaltyPayment(
        @WebParam(name = "request", targetNamespace = "")
        ServiceUpdatePenaltyPaymentRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100424_borderRegisteredPassengerInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100424_borderRegisteredPassengerInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100424BorderRegisteredPassengerInfo")
    @ResponseWrapper(localName = "WS100424_borderRegisteredPassengerInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100424BorderRegisteredPassengerInfoResponse")
    public ServiceResponse ws100424BorderRegisteredPassengerInfo(
        @WebParam(name = "request", targetNamespace = "")
        VehicleBorderPassRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100407_getDriverLicenseInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100407_getDriverLicenseInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100407GetDriverLicenseInfo")
    @ResponseWrapper(localName = "WS100407_getDriverLicenseInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100407GetDriverLicenseInfoResponse")
    public ServiceResponse ws100407GetDriverLicenseInfo(
        @WebParam(name = "request", targetNamespace = "")
        ServiceDriverLicenseInfoData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100404_getECDataInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100404_getECDataInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100404GetECDataInfo")
    @ResponseWrapper(localName = "WS100404_getECDataInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100404GetECDataInfoResponse")
    public ServiceResponse ws100404GetECDataInfo(
        @WebParam(name = "request", targetNamespace = "")
        GetECDataRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100418_vehicleLimitedInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100418_vehicleLimitedInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100418VehicleLimitedInfo")
    @ResponseWrapper(localName = "WS100418_vehicleLimitedInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100418VehicleLimitedInfoResponse")
    public ServiceResponse ws100418VehicleLimitedInfo(
        @WebParam(name = "request", targetNamespace = "")
        VehicleLimitedRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100415_vehicleInfoList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100415_vehicleInfoList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100415VehicleInfoList")
    @ResponseWrapper(localName = "WS100415_vehicleInfoListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100415VehicleInfoListResponse")
    public ServiceResponse ws100415VehicleInfoList(
        @WebParam(name = "request", targetNamespace = "")
        VehicleListRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100414_getImportExportItemList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100414_getImportExportItemList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100414GetImportExportItemList")
    @ResponseWrapper(localName = "WS100414_getImportExportItemListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100414GetImportExportItemListResponse")
    public ServiceResponse ws100414GetImportExportItemList(
        @WebParam(name = "request", targetNamespace = "")
        GetImportExportRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100422_getCitizenPenaltyList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100422_getCitizenPenaltyList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100422GetCitizenPenaltyList")
    @ResponseWrapper(localName = "WS100422_getCitizenPenaltyListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100422GetCitizenPenaltyListResponse")
    public ServiceResponse ws100422GetCitizenPenaltyList(
        @WebParam(name = "request", targetNamespace = "")
        CitizenPenaltyListRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100409_getVehicleInspectionInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100409_getVehicleInspectionInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100409GetVehicleInspectionInfo")
    @ResponseWrapper(localName = "WS100409_getVehicleInspectionInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100409GetVehicleInspectionInfoResponse")
    public ServiceResponse ws100409GetVehicleInspectionInfo(
        @WebParam(name = "request", targetNamespace = "")
        VehicleInspectionRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100427_transportOrganizationCarsInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100427_transportOrganizationCarsInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100427TransportOrganizationCarsInfo")
    @ResponseWrapper(localName = "WS100427_transportOrganizationCarsInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100427TransportOrganizationCarsInfoResponse")
    public ServiceResponse ws100427TransportOrganizationCarsInfo(
        @WebParam(name = "request", targetNamespace = "")
        ServiceVehicleOrganizationRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100436_vehicleLegalEntityInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100436_vehicleLegalEntityInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100436VehicleLegalEntityInfo")
    @ResponseWrapper(localName = "WS100436_vehicleLegalEntityInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100436VehicleLegalEntityInfoResponse")
    public ServiceResponse ws100436VehicleLegalEntityInfo(
        @WebParam(name = "request", targetNamespace = "")
        VehicleLegalEntityInfoRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100401_getVehicleInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100401_getVehicleInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100401GetVehicleInfo")
    @ResponseWrapper(localName = "WS100401_getVehicleInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100401GetVehicleInfoResponse")
    public ServiceResponse ws100401GetVehicleInfo(
        @WebParam(name = "request", targetNamespace = "")
        VehicleRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100423_borderRegisteredTransportInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100423_borderRegisteredTransportInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100423BorderRegisteredTransportInfo")
    @ResponseWrapper(localName = "WS100423_borderRegisteredTransportInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100423BorderRegisteredTransportInfoResponse")
    public ServiceResponse ws100423BorderRegisteredTransportInfo(
        @WebParam(name = "request", targetNamespace = "")
        VehicleBorderPassRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100406_getCitizenVehicleList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100406_getCitizenVehicleList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100406GetCitizenVehicleList")
    @ResponseWrapper(localName = "WS100406_getCitizenVehicleListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100406GetCitizenVehicleListResponse")
    public ServiceResponse ws100406GetCitizenVehicleList(
        @WebParam(name = "request", targetNamespace = "")
        VehicleRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100412_getTransportInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100412_getTransportInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100412GetTransportInfo")
    @ResponseWrapper(localName = "WS100412_getTransportInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100412GetTransportInfoResponse")
    public ServiceResponse ws100412GetTransportInfo(
        @WebParam(name = "request", targetNamespace = "")
        TransportRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100419_vehicleBorderPass")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100419_vehicleBorderPass", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100419VehicleBorderPass")
    @ResponseWrapper(localName = "WS100419_vehicleBorderPassResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100419VehicleBorderPassResponse")
    public ServiceResponse ws100419VehicleBorderPass(
        @WebParam(name = "request", targetNamespace = "")
        VehicleBorderPassRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100411_vehicleImportInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100411_vehicleImportInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100411VehicleImportInfo")
    @ResponseWrapper(localName = "WS100411_vehicleImportInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100411VehicleImportInfoResponse")
    public ServiceResponse ws100411VehicleImportInfo(
        @WebParam(name = "request", targetNamespace = "")
        ServiceVehicleImportInfoData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100420_getOrganizationVehicleList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100420_getOrganizationVehicleList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100420GetOrganizationVehicleList")
    @ResponseWrapper(localName = "WS100420_getOrganizationVehicleListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100420GetOrganizationVehicleListResponse")
    public ServiceResponse ws100420GetOrganizationVehicleList(
        @WebParam(name = "request", targetNamespace = "")
        ServiceVehicleOrganizationRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100429_transportConclutionResponseInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100429_transportConclutionResponseInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100429TransportConclutionResponseInfo")
    @ResponseWrapper(localName = "WS100429_transportConclutionResponseInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100429TransportConclutionResponseInfoResponse")
    public ServiceResponse ws100429TransportConclutionResponseInfo(
        @WebParam(name = "request", targetNamespace = "")
        GetECDataRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100425_getImportExportItemExpandList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100425_getImportExportItemExpandList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100425GetImportExportItemExpandList")
    @ResponseWrapper(localName = "WS100425_getImportExportItemExpandListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100425GetImportExportItemExpandListResponse")
    public ServiceResponse ws100425GetImportExportItemExpandList(
        @WebParam(name = "request", targetNamespace = "")
        GetImportExportRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100431_permittedVehiclesList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100431_permittedVehiclesList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100431PermittedVehiclesList")
    @ResponseWrapper(localName = "WS100431_permittedVehiclesListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100431PermittedVehiclesListResponse")
    public ServiceResponse ws100431PermittedVehiclesList(
        @WebParam(name = "request", targetNamespace = "")
        PermittedVehiclesListRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100421_getPreOwnedVehicle")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100421_getPreOwnedVehicle", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100421GetPreOwnedVehicle")
    @ResponseWrapper(localName = "WS100421_getPreOwnedVehicleResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100421GetPreOwnedVehicleResponse")
    public ServiceResponse ws100421GetPreOwnedVehicle(
        @WebParam(name = "request", targetNamespace = "")
        VehicleRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100413_getInternationalDriverLicenseInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100413_getInternationalDriverLicenseInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100413GetInternationalDriverLicenseInfo")
    @ResponseWrapper(localName = "WS100413_getInternationalDriverLicenseInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100413GetInternationalDriverLicenseInfoResponse")
    public ServiceResponse ws100413GetInternationalDriverLicenseInfo(
        @WebParam(name = "request", targetNamespace = "")
        InternationalDriverLicenseRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100433_unlicensedVehiclesList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100433_unlicensedVehiclesList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100433UnlicensedVehiclesList")
    @ResponseWrapper(localName = "WS100433_unlicensedVehiclesListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100433UnlicensedVehiclesListResponse")
    public ServiceResponse ws100433UnlicensedVehiclesList(
        @WebParam(name = "request", targetNamespace = "")
        PermittedVehiclesListRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100434_checkECLIcenseFromKiosk")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100434_checkECLIcenseFromKiosk", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100434CheckECLIcenseFromKiosk")
    @ResponseWrapper(localName = "WS100434_checkECLIcenseFromKioskResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100434CheckECLIcenseFromKioskResponse")
    public ServiceResponse ws100434CheckECLIcenseFromKiosk(
        @WebParam(name = "request", targetNamespace = "")
        CheckECLIcenseFromKioskRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100437_vehicleLegalEntityTotal")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100437_vehicleLegalEntityTotal", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100437VehicleLegalEntityTotal")
    @ResponseWrapper(localName = "WS100437_vehicleLegalEntityTotalResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100437VehicleLegalEntityTotalResponse")
    public ServiceResponse ws100437VehicleLegalEntityTotal(
        @WebParam(name = "request", targetNamespace = "")
        OrgRegnumRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100428_transportCheckGPSPayment")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100428_transportCheckGPSPayment", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100428TransportCheckGPSPayment")
    @ResponseWrapper(localName = "WS100428_transportCheckGPSPaymentResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100428TransportCheckGPSPaymentResponse")
    public ServiceResponse ws100428TransportCheckGPSPayment(
        @WebParam(name = "request", targetNamespace = "")
        TransportCheckGPSPaymentRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100438_getPreOwnedOrgVehicleTotal")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100438_getPreOwnedOrgVehicleTotal", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100438GetPreOwnedOrgVehicleTotal")
    @ResponseWrapper(localName = "WS100438_getPreOwnedOrgVehicleTotalResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100438GetPreOwnedOrgVehicleTotalResponse")
    public ServiceResponse ws100438GetPreOwnedOrgVehicleTotal(
        @WebParam(name = "request", targetNamespace = "")
        OrgRegnumRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100402_getVehicleOwnerHistoryList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100402_getVehicleOwnerHistoryList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100402GetVehicleOwnerHistoryList")
    @ResponseWrapper(localName = "WS100402_getVehicleOwnerHistoryListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100402GetVehicleOwnerHistoryListResponse")
    public ServiceResponse ws100402GetVehicleOwnerHistoryList(
        @WebParam(name = "request", targetNamespace = "")
        VehicleRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100426_transportGetOrganizationInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100426_transportGetOrganizationInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100426TransportGetOrganizationInfo")
    @ResponseWrapper(localName = "WS100426_transportGetOrganizationInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100426TransportGetOrganizationInfoResponse")
    public ServiceResponse ws100426TransportGetOrganizationInfo(
        @WebParam(name = "request", targetNamespace = "")
        ServiceVehicleOrganizationRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100435_getPreOwnedVehicleWithOrgRegnum")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100435_getPreOwnedVehicleWithOrgRegnum", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100435GetPreOwnedVehicleWithOrgRegnum")
    @ResponseWrapper(localName = "WS100435_getPreOwnedVehicleWithOrgRegnumResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100435GetPreOwnedVehicleWithOrgRegnumResponse")
    public ServiceResponse ws100435GetPreOwnedVehicleWithOrgRegnum(
        @WebParam(name = "request", targetNamespace = "")
        VehicleLegalEntityInfoRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100432_getVehicleInspectionDataByPlateNo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100432_getVehicleInspectionDataByPlateNo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100432GetVehicleInspectionDataByPlateNo")
    @ResponseWrapper(localName = "WS100432_getVehicleInspectionDataByPlateNoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100432GetVehicleInspectionDataByPlateNoResponse")
    public ServiceResponse ws100432GetVehicleInspectionDataByPlateNo(
        @WebParam(name = "request", targetNamespace = "")
        VehicleInspectionByPlateNoRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100416_getOwnerInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100416_getOwnerInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100416GetOwnerInfo")
    @ResponseWrapper(localName = "WS100416_getOwnerInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100416GetOwnerInfoResponse")
    public ServiceResponse ws100416GetOwnerInfo(
        @WebParam(name = "request", targetNamespace = "")
        OwnerRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100417_specialDriverInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100417_specialDriverInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100417SpecialDriverInfo")
    @ResponseWrapper(localName = "WS100417_specialDriverInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100417SpecialDriverInfoResponse")
    public ServiceResponse ws100417SpecialDriverInfo(
        @WebParam(name = "request", targetNamespace = "")
        SpecialDriverRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100405_getVehicleTaxInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100405_getVehicleTaxInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100405GetVehicleTaxInfo")
    @ResponseWrapper(localName = "WS100405_getVehicleTaxInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100405GetVehicleTaxInfoResponse")
    public ServiceResponse ws100405GetVehicleTaxInfo(
        @WebParam(name = "request", targetNamespace = "")
        VehicleRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100403_getVehiclePenaltyList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100403_getVehiclePenaltyList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100403GetVehiclePenaltyList")
    @ResponseWrapper(localName = "WS100403_getVehiclePenaltyListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100403GetVehiclePenaltyListResponse")
    public ServiceResponse ws100403GetVehiclePenaltyList(
        @WebParam(name = "request", targetNamespace = "")
        ServiceVehiclePenaltyInfoRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypTransport.ServiceResponse
     */
    @WebMethod(operationName = "WS100410_isVehicleCheck")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100410_isVehicleCheck", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100410IsVehicleCheck")
    @ResponseWrapper(localName = "WS100410_isVehicleCheckResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypTransport.WS100410IsVehicleCheckResponse")
    public ServiceResponse ws100410IsVehicleCheck(
        @WebParam(name = "request", targetNamespace = "")
        VehicleRequestData request);

}
