
package mn.gov.ema.emongolia.data.XypHealth;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HealthServiceService", targetNamespace = "http://health.xyp.gov.mn/", wsdlLocation = "https://xyp.gov.mn/health-1.5.0/ws?WSDL")
public class HealthServiceService
    extends Service
{

    private final static URL HEALTHSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException HEALTHSERVICESERVICE_EXCEPTION;
    private final static QName HEALTHSERVICESERVICE_QNAME = new QName("http://health.xyp.gov.mn/", "HealthServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://xyp.gov.mn/health-1.5.0/ws?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HEALTHSERVICESERVICE_WSDL_LOCATION = url;
        HEALTHSERVICESERVICE_EXCEPTION = e;
    }

    public HealthServiceService() {
        super(__getWsdlLocation(), HEALTHSERVICESERVICE_QNAME);
    }

    public HealthServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HEALTHSERVICESERVICE_QNAME, features);
    }

    public HealthServiceService(URL wsdlLocation) {
        super(wsdlLocation, HEALTHSERVICESERVICE_QNAME);
    }

    public HealthServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HEALTHSERVICESERVICE_QNAME, features);
    }

    public HealthServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HealthServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HealthService
     */
    @WebEndpoint(name = "HealthServicePort")
    public HealthService getHealthServicePort() {
        return super.getPort(new QName("http://health.xyp.gov.mn/", "HealthServicePort"), HealthService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HealthService
     */
    @WebEndpoint(name = "HealthServicePort")
    public HealthService getHealthServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://health.xyp.gov.mn/", "HealthServicePort"), HealthService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HEALTHSERVICESERVICE_EXCEPTION!= null) {
            throw HEALTHSERVICESERVICE_EXCEPTION;
        }
        return HEALTHSERVICESERVICE_WSDL_LOCATION;
    }

}
