
package mn.gov.ema.emongolia.data.XypHealth;

import mn.gov.ema.emongolia.data.ServiceResponse.ServiceResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HealthService", targetNamespace = "http://health.xyp.gov.mn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HealthService {


    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypHealth.ServiceResponse
     */
    @WebMethod(operationName = "WS300110_eHealthOnlineAppointmentOrder")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS300110_eHealthOnlineAppointmentOrder", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300110EHealthOnlineAppointmentOrder")
    @ResponseWrapper(localName = "WS300110_eHealthOnlineAppointmentOrderResponse", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300110EHealthOnlineAppointmentOrderResponse")
    public ServiceResponse ws300110EHealthOnlineAppointmentOrder(
        @WebParam(name = "request", targetNamespace = "")
        EHealthAppointmentOrderRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypHealth.ServiceResponse
     */
    @WebMethod(operationName = "WS300103_eHealthGetAnalysisResult")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS300103_eHealthGetAnalysisResult", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300103EHealthGetAnalysisResult")
    @ResponseWrapper(localName = "WS300103_eHealthGetAnalysisResultResponse", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300103EHealthGetAnalysisResultResponse")
    public ServiceResponse ws300103EHealthGetAnalysisResult(
        @WebParam(name = "request", targetNamespace = "")
        EHealthGetAnalysisResultRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypHealth.ServiceResponse
     */
    @WebMethod(operationName = "WS300114_eHealthListService")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS300114_eHealthListService", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300114EHealthListService")
    @ResponseWrapper(localName = "WS300114_eHealthListServiceResponse", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300114EHealthListServiceResponse")
    public ServiceResponse ws300114EHealthListService(
        @WebParam(name = "request", targetNamespace = "")
        EHealthListRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypHealth.ServiceResponse
     */
    @WebMethod(operationName = "WS300111_eHealthTimeOrderApprove")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS300111_eHealthTimeOrderApprove", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300111EHealthTimeOrderApprove")
    @ResponseWrapper(localName = "WS300111_eHealthTimeOrderApproveResponse", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300111EHealthTimeOrderApproveResponse")
    public ServiceResponse ws300111EHealthTimeOrderApprove(
        @WebParam(name = "request", targetNamespace = "")
        EHealthTimeOrderApproveRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypHealth.ServiceResponse
     */
    @WebMethod(operationName = "WS300108_eHealthGetFreeTimeList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS300108_eHealthGetFreeTimeList", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300108EHealthGetFreeTimeList")
    @ResponseWrapper(localName = "WS300108_eHealthGetFreeTimeListResponse", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300108EHealthGetFreeTimeListResponse")
    public ServiceResponse ws300108EHealthGetFreeTimeList(
        @WebParam(name = "request", targetNamespace = "")
        EHealthGetFreeTimeRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypHealth.ServiceResponse
     */
    @WebMethod(operationName = "WS300117_earlyDetectionService")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS300117_earlyDetectionService", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300117EarlyDetectionService")
    @ResponseWrapper(localName = "WS300117_earlyDetectionServiceResponse", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300117EarlyDetectionServiceResponse")
    public ServiceResponse ws300117EarlyDetectionService(
        @WebParam(name = "request", targetNamespace = "")
        EarlyDetectionRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypHealth.ServiceResponse
     */
    @WebMethod(operationName = "WS300101_getInsuranceFee")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS300101_getInsuranceFee", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300101GetInsuranceFee")
    @ResponseWrapper(localName = "WS300101_getInsuranceFeeResponse", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300101GetInsuranceFeeResponse")
    public ServiceResponse ws300101GetInsuranceFee(
        @WebParam(name = "request", targetNamespace = "")
        RegisterRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypHealth.ServiceResponse
     */
    @WebMethod(operationName = "WS300106_eHealthCreatePatient")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS300106_eHealthCreatePatient", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300106EHealthCreatePatient")
    @ResponseWrapper(localName = "WS300106_eHealthCreatePatientResponse", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300106EHealthCreatePatientResponse")
    public ServiceResponse ws300106EHealthCreatePatient(
        @WebParam(name = "request", targetNamespace = "")
        EHealthCreatePatientRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypHealth.ServiceResponse
     */
    @WebMethod(operationName = "WS300109_eHealthOnlineTimeOrderList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS300109_eHealthOnlineTimeOrderList", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300109EHealthOnlineTimeOrderList")
    @ResponseWrapper(localName = "WS300109_eHealthOnlineTimeOrderListResponse", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300109EHealthOnlineTimeOrderListResponse")
    public ServiceResponse ws300109EHealthOnlineTimeOrderList(
        @WebParam(name = "request", targetNamespace = "")
        EhealtBasicRequestData request);

    /**
     * @param request
     * @return returns mn.gov.itc.emongolia.data.XypHealth.ServiceResponse
     */
    @WebMethod(operationName = "WS300116_getBloodTypeService")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS300116_getBloodTypeService", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300116GetBloodTypeService")
    @ResponseWrapper(localName = "WS300116_getBloodTypeServiceResponse", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300116GetBloodTypeServiceResponse")
    public ServiceResponse ws300116GetBloodTypeService(
        @WebParam(name = "request", targetNamespace = "")
        RegisterRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypHealth.ServiceResponse
     */
    @WebMethod(operationName = "WS300107_eHealthGetMedicalServices")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS300107_eHealthGetMedicalServices", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300107EHealthGetMedicalServices")
    @ResponseWrapper(localName = "WS300107_eHealthGetMedicalServicesResponse", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300107EHealthGetMedicalServicesResponse")
    public ServiceResponse ws300107EHealthGetMedicalServices(
        @WebParam(name = "request", targetNamespace = "")
        EHealthGetMedicalServicesRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypHealth.ServiceResponse
     */
    @WebMethod(operationName = "WS300118_covidPCRLastResultInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS300118_covidPCRLastResultInfo", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300118CovidPCRLastResultInfo")
    @ResponseWrapper(localName = "WS300118_covidPCRLastResultInfoResponse", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300118CovidPCRLastResultInfoResponse")
    public ServiceResponse ws300118CovidPCRLastResultInfo(
        @WebParam(name = "request", targetNamespace = "")
        RegisterRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypHealth.ServiceResponse
     */
    @WebMethod(operationName = "WS300119_medicineImportInsert")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS300119_medicineImportInsert", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300119MedicineImportInsert")
    @ResponseWrapper(localName = "WS300119_medicineImportInsertResponse", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300119MedicineImportInsertResponse")
    public ServiceResponse ws300119MedicineImportInsert(
        @WebParam(name = "request", targetNamespace = "")
        MedicineImportInsertRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypHealth.ServiceResponse
     */
    @WebMethod(operationName = "WS300115_pcrPositiveInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS300115_pcrPositiveInfo", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300115PcrPositiveInfo")
    @ResponseWrapper(localName = "WS300115_pcrPositiveInfoResponse", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300115PcrPositiveInfoResponse")
    public ServiceResponse ws300115PcrPositiveInfo(
        @WebParam(name = "request", targetNamespace = "")
        PcrPositiveRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypHealth.ServiceResponse
     */
    @WebMethod(operationName = "WS300102_eHealthGetHospitals")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS300102_eHealthGetHospitals", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300102EHealthGetHospitals")
    @ResponseWrapper(localName = "WS300102_eHealthGetHospitalsResponse", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300102EHealthGetHospitalsResponse")
    public ServiceResponse ws300102EHealthGetHospitals(
        @WebParam(name = "request", targetNamespace = "")
        RegisterRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypHealth.ServiceResponse
     */
    @WebMethod(operationName = "WS300112_eHealthTimeOrderCancel")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS300112_eHealthTimeOrderCancel", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300112EHealthTimeOrderCancel")
    @ResponseWrapper(localName = "WS300112_eHealthTimeOrderCancelResponse", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300112EHealthTimeOrderCancelResponse")
    public ServiceResponse ws300112EHealthTimeOrderCancel(
        @WebParam(name = "request", targetNamespace = "")
        EHealthTimeOrderApproveRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypHealth.ServiceResponse
     */
    @WebMethod(operationName = "WS300105_eHealthCheckPatientExists")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS300105_eHealthCheckPatientExists", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300105EHealthCheckPatientExists")
    @ResponseWrapper(localName = "WS300105_eHealthCheckPatientExistsResponse", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300105EHealthCheckPatientExistsResponse")
    public ServiceResponse ws300105EHealthCheckPatientExists(
        @WebParam(name = "request", targetNamespace = "")
        EhealtBasicRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypHealth.ServiceResponse
     */
    @WebMethod(operationName = "WS300113_eHealthCitizenAnalisysInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS300113_eHealthCitizenAnalisysInfo", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300113EHealthCitizenAnalisysInfo")
    @ResponseWrapper(localName = "WS300113_eHealthCitizenAnalisysInfoResponse", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300113EHealthCitizenAnalisysInfoResponse")
    public ServiceResponse ws300113EHealthCitizenAnalisysInfo(
        @WebParam(name = "request", targetNamespace = "")
        EHealthCitizenAnalysisRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.itc.emongolia.data.XypHealth.ServiceResponse
     */
    @WebMethod(operationName = "WS300104_eHealthGetAnalysisDates")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS300104_eHealthGetAnalysisDates", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300104EHealthGetAnalysisDates")
    @ResponseWrapper(localName = "WS300104_eHealthGetAnalysisDatesResponse", targetNamespace = "http://health.xyp.gov.mn/", className = "mn.gov.itc.emongolia.data.XypHealth.WS300104EHealthGetAnalysisDatesResponse")
    public ServiceResponse ws300104EHealthGetAnalysisDates(
        @WebParam(name = "request", targetNamespace = "")
        EhealtBasicRequestData request);

}
