name: Push inquiry-backend docker image

env:
  DOCKER_REGISTRY: hub.e-mongolia.mn/e-mongolia-inquiry-backend

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Maven clean & install
        run: mvn clean install

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-inquiry-backend-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-inquiry-backend-

      - name: Login to E-Mongola Docker HUB
        id: login-ecr
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.SECRET_USERNAME }}
          password: ${{ secrets.SECRET_PASSWORD }}

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: ./inquiry-backend
          file: ./inquiry-backend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}:latest
            ${{ env.DOCKER_REGISTRY }}:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
 